[package]
name = "rss2email"
version = "0.1.0"
authors = ["Jan CW Kroeze <jcwkroeze@pm.me>"]
edition = "2018"

[dependencies]
docopt = "1.1.0"
reqwest = { version = "0.11", features = ["blocking"] }
sendgrid = "0.16.0"
serde = "1.0.123"
sqlite = "0.25.3"
xml-rs = "0.8"
